### ISSUE TITLE
std.rand() is not cryptographically secure.

### ISSUE THREAD

**Issue by oridb** [oridb/mc#10]
The algorithm should be cryptographically secure and properly seeded by default. There should be a way of setting it up for deterministic output, but this should be explicitly set.

**Comment by kirbyfan64** [comment]
Python actually has two random number generators: a default, non-crypto one; and one that's cryptographically secure, based on the system's random generator (e.g. `/dev/urandom`).

**Comment by oridb** [comment]
There's also this: http://www.pcg-random.org/posts/ease-of-use-without-loss-of-power.html

Which is worth a read.

**Comment by oridb** [comment]
Note, there's nothing particularly mysterious or difficult about the API design; it just comes down to sitting down and writing code.

**Comment by oridb** [comment]
I think std.rand is going to remain insecure, but now there's crypto.rand:

     http://git.eigenstate.org/ori/mc.git/tree/lib/crypto/rand.myr
