### ISSUE TITLE
Miscompilation

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#100]
```
use std

const cmp = {l : (byte[:], uint64), r : (byte[:], uint64)
	var lk, rk
	
	(lk, _) = l
	(rk, _) = r
	
	-> std.strcmp(lk, rk)
}

const main = {
	var index
	
	index = [("abc", 0), ("def", 444)][:]
	std.put("{}\n", std.lsearch(index, ("def", 0), cmp))
}
```
```
ac@nomad:~/src/bpy$ mbld -R ~/Desktop/bug/bug.myr 
/tmp/runmyr2543049647...
	6m	/home/ac/Desktop/bug/bug.myr 
	ld	-o /tmp/runmyr2543049647 /usr/local/lib/myr/_myrrt.o /home/ac/Desktop/bug/bug.o -L/usr/local/lib/myr -lstd -lsys 
	/tmp/runmyr2543049647	
`Some 1
```

Somehow `Some 1 is being found, even though it is not in the list at all.

**Comment by oridb** [comment]
Are you sure it's not a problem with bsearch? I would be suspicious of that.
On Mar 6, 2016 12:32 AM, andrewchambers <notifications@github.com> wrote:use std

type reader = struct
    index : std.option((byte[:], uint64)[:])
;;

const koffsetcmp = {l : (byte[:], uint64), r : (byte[:], uint64)

    var lk, rk

    (lk, _) = l
    (rk, _) = r

    -> std.strcmp(lk, rk)
}

const has = {r, k
    var index

    match r.index
    | `std.None:
        std.fatal("bpack read without loading index\n")
    | `std.Some idx:
        index = idx
    ;;
    -> std.bsearch(index, (k, 0), koffsetcmp)
}

const main = {
    var r : reader

    r.index = `std.Some [("abc", 0), ("def", 444)][:]

    std.put("{}\n", has(r, "def"))
}


ac@nomad:~/src/bpy$ mbld -R ~/Desktop/bug/bug.myr 
/tmp/runmyr2543049647...
    6m  /home/ac/Desktop/bug/bug.myr 
    ld  -o /tmp/runmyr2543049647 /usr/local/lib/myr/_myrrt.o /home/ac/Desktop/bug/bug.o -L/usr/local/lib/myr -lstd -lsys 
    /tmp/runmyr2543049647   
`Some 1


Somehow `Some 1 is being found, even though it is not in the list at all.

**Comment by andrewchambers** [comment]
just updated and reduced it to lsearch, it is really strange because this code worked before I did a refactor.

**Comment by andrewchambers** [comment]
updated the main comment*

**Comment by andrewchambers** [comment]
oh fuck, it returns the index, not the value. I'm an idiot
