### ISSUE TITLE
Invalid identifier causes an assertion failure in the compiler

### ISSUE THREAD

**Issue by marchelzo** [oridb/mc#113]
When you try to compile code where an identifier contains more than one `.`, this happens:

```
Assertion failed: (!ns || !n->name.ns || !strcmp(n->name.ns, ns)), function setns, file node.c, line 484.
CRASH: "6m bad.myr"
```

Here is the program that I tried it with:

```
const main = {
        var a.b.c = 4
}
```

Perhaps it would be better to instead fail with an appropriate error message.

**Comment by andrewchambers** [comment]
Nice find, thanks for reporting.
