### ISSUE TITLE
Executing test commands from README yields "nothing satisfies build.use for test.o"

### ISSUE THREAD

**Issue by FrankRuben** [oridb/mc#146]
Hi,
compile went fine, invocation of compiler works fine and compiling the fizzbuzz sample from the README also works (after adding ~/myrddin/bin to the PATH).
But both invocations `mbld -R test.myr` and `mbld -b binary test.myr` in the directory of test.myr lead to the above mentioned error `nothing satisfies build.use for test.o`.
I found that error message in the source, but no idea how solve that from there.
Btw.: interesting language.
Regards, Frank

**Comment by oridb** [comment]
Does your code have a line:    use "build"In test.myr? If so, you need to pass all source files in to the mbld command. If not, I would like to see what the input is.On Sep 23, 2017 15:21, Frank Ruben <notifications@github.com> wrote:Hi,
compile went fine, invocation of compiler works fine and compiling the fizzbuzz sample from the README also works (after adding ~/myrddin/bin to the PATH).
But both invocations mbld -R test.myr and mbld -b binary test.myr in the directory of test.myr lead to the above mentioned error nothing satisfies build.use for test.o.
I found that error message in the source, but no idea how solve that from there.
Btw.: interesting language.
Regards, Frank

**Comment by FrankRuben** [comment]
Thanks for the quick answer - and I think I got it: the README tells me to run `mbld -R test.myr` or `mbld -b binary test.myr` - and that's what I did, but not with _my code_, but with a test.myr that I found in the repo.

But that's probably not what you meant to be a test program, but a library to run tests and the `test.myr` mentioned in the README seems to be just a dummy name for some self-written source file.

Sorry for the confusion, Frank

**Comment by oridb** [comment]
Yep, that's exactly what it is. I'll rename it to prevent confusion.
