### ISSUE TITLE
"out of bounds access" when using custom formatting with weekday modifiers  

### ISSUE THREAD

**Issue by FrankRuben** [oridb/mc#148]
Hi,

when using some code similar to the formatting sample in the library documentation,
I'm getting an "out of bounds access" error.
This can be fixed by changing the following lines in ~/date/fmt.myr (from `d.day` to `d.wday`):

```
	| 'a':	std.sbfmt(sb, "{}", _names.abbrevday[d.wday])
	| 'A':	std.sbfmt(sb, "{}", _names.fullday[d.wday])
```

HTH, Frank

**Comment by oridb** [comment]
Fixed, and added tests. Feel free to send a pull request next time, or toss a patch on the mailing list.
