### ISSUE TITLE
Type description symbol is not created correctly

### ISSUE THREAD

**Issue by oridb** [oridb/mc#17]
When attempting to pass an unexported struct to varargs, the type info symbol is either not created, or created with the wrong name

    use std
    
    type foo = struct
    	x : int
    ;;
    
    const main = {
    	var x : foo = [.x=123]
    	std.put("{}", x)
    }

produces the following error:

    Undefined symbols for architecture x86_64:
    "__tydesc$foo$33", referenced from:
        __tydesc$1484 in test.o
    ld: symbol(s) not found for inferred architecture x86_64

To work around it, the type can be exported:

    pkg =
            type foo
    ;;

This is not ideal.

**Comment by kirbyfan64** [comment]
FYI, you can write commit messages like `fixes #17`, and GitHub will close it automatically. Also, any time you use the issue number in a commit message (like `related to #20`), GitHub will put a link to the relevant commit in the issue.
