### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [oridb/mc#176]
I suggest to add the key word “const” to the type specifiers for parameters like the following.
- path (function “[loaduse](https://github.com/oridb/mc/blob/e4e8fa6f7760221f843a924f058d11b58041db64/parse/parse.h#L556)”)
- ns (function “[setns](https://github.com/oridb/mc/blob/e4e8fa6f7760221f843a924f058d11b58041db64/parse/parse.h#L538)”)

Would you like to apply the advices from [an article](https://en.wikipedia.org/wiki/Const_%28computer_programming%29#Consequences "Description for const-correctness") to more places in your source files?

**Comment by oridb** [comment]
> Would you like to apply the advices from an article to more places in your source files?

No, not really.
