### ISSUE TITLE
Pattern-matching a value causes Infinite loops 

### ISSUE THREAD

**Issue by typeless** [oridb/mc#183]
```
use std

type ty = union
        `Tyarray int
        `Other
;;

type srcloc = struct
        file    : byte[:]
        line    : int
;;

type tydef = struct
        ty      : ty
        loc     : srcloc
        fixed   : bool
;;

const istyarray = {t
        match t
        | [.ty=`Tyarray 1 ]:    -> true
        | _:                    -> false
        ;;
}

const main = {
        var b : tydef = [.ty = `Other]
        var v = istyarray(b)

        std.put("{}\n", v)
}

```
Tested with the master (9664143)
I expected that it should show 'false'. It's not obvious how this could generate an infinite loop.
Not an urgent issue.

**Comment by oridb** [comment]
That's definitely an issue. Thanks, will look into it in the next little while.

**Comment by oridb** [comment]
I'm probably going to take the time to actually clean up mi/match.c while I do this, so this may take a bit of time to fix. I'll see if I can put in a quick fix in the mean time.

**Comment by typeless** [comment]
No problem. Take your time.
