### ISSUE TITLE
proposal: support '--' to pass CLI arguments to the program run by mbld -R

### ISSUE THREAD

**Issue by typeless** [oridb/mc#194]

**Comment by typeless** [comment]
I am trying to implement it.

**Comment by oridb** [comment]
Proposal sounds good -- there are two ways I can see to handle it. Right now, the `-R` option actually takes a list of files that compose a program. We can simply change that to one file, and make that into `-R`'s option list. This means that you don't even need `--`, you can do `mbld -R foo.myr arg list`.

The other option will be finding some way to feed back the position of '--' in the arg list from the argument parser. Right now that information ls lost.

Either option is fine by me; I don't think I've ever passed multiple files to `mbld -R`.

**Comment by typeless** [comment]
@oridb Okay. I'll go with the first option.

**Comment by typeless** [comment]
The pr has been merged.
