### ISSUE TITLE
Label emitted twice causing assembler error

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#28]
reduced test case

```
ac@nomad:~/Desktop/bug$ mbld -b bug bug.myr 
bug...
	6m	bug.myr 
/tmp/tmp567ff4e310c49-bug.myr.s: Assembler messages:
/tmp/tmp567ff4e310c49-bug.myr.s:112: Error: symbol `.L12' is already defined
Couldn't run assembler
CRASH: "6m bug.myr"

```

```
const foo = {
	for var i = 0 ; i != 1 ; i++
		match 0
		| _ :
			-> true
			match 0
			| 1:
			| _ :
				-> true
			;;
		;;
	;;	
	-> false
}

```

**Comment by oridb** [comment]
This looks a lot like an issue with trimming dead blocks in the CFG. When we decide that a block is unreachable, or can be merged with another block, we move the labels and delete the block.

Here, it seems like we're not removing the unreachable block after moving the labels, so it seems like they're getting emitted twice.
