### ISSUE TITLE
build incorrectly uses installed tools

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#35]
```
$ git checkout HEAD~70
$ git clean -fxd
$ make install
$ git checkout master
$ git clean -fxd
$ make
...
Leaving directory 'lib/sys'
Entering directory 'lib/std'
libstd.a...
library sys: usefile version 10 unknown
...
libregex.a...
library std: usefile version 10 unknown
library sys: usefile version 10 unknown
... etc
```

The usefile version warnings are unexpected and seem like a red flag that some of the old tools are being used even though bootstrapping should build everything fresh.

**Comment by oridb** [comment]
I can't reproduce this -- checking out the old version seems to have the issue, but the newest commit doesn't. Tested on OSX.

**Comment by oridb** [comment]
Also seems to work on FreeBSD

**Comment by oridb** [comment]
Oh. I see what's happening -- if you're cleaning, it uses the installed version of mbld, which isn't aware of the newest usefile version, which causes warnings.

I don't think this is solvable, or necessarily a bug.
