### ISSUE TITLE
logic error leading to potential null ptr dereference

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#38]
https://github.com/oridb/mc/blob/4c1c6f77962993b62a082bfd2d91bde671cdc329/parse/infer.c#L2104

if d can be null, then line 2106 will dereference it. if it can't be null this check is dead code. (found with clang static analysis)

**Comment by oridb** [comment]
Can't be null -- if there's a key in the hash table, there needs to be a value as well. If there isn't, there's a serious bug elsewhere.

**Comment by andrewchambers** [comment]
doh, not dead code, just useless check. no big deal.
