### ISSUE TITLE
implement a builder

### ISSUE THREAD

**Issue by oridb** [oridb/mc#61]
Every diff should be tested on all supported systems.

**Comment by kirbyfan64** [comment]
Like Travis CI? I could try to help set it up!

**Comment by oridb** [comment]
I have never used Travis, so I don't actually know if it can handle what we'd need -- Basically, I'd want to farm out builds to VMs (or physical hardware) for tests.

The other wish is that the builders would be able to regenerate the bootstrap scripts and submit pull requests if they've changed.

I suspect there's going to be some custom scripts for this.

**Comment by andrewchambers** [comment]
Travis might not be flexible enough to support everything we want. Travis requires a config file in the root of he repo, and gives you a linux vm to run a single script in.

**Comment by oridb** [comment]
Can we run VMs on the linux VM? :)

**Comment by kirbyfan64** [comment]
It works on multiple OSs, but I'm not sure about the PR submission.

**Comment by andrewchambers** [comment]
Apparently travis supports OSX. I think we may be able to run a freebsd from linux.

The go repo has a set of scripts for generating builder images from scratch automatically which we could take.

**Comment by oridb** [comment]
Note that I've got hardware in a data center that we should be able to run VMs on now, if we need that, and I'm willing to spend a bit of money to add a Mac Mini, or whatever else we need.

**Comment by andrewchambers** [comment]
I have setup buildbot, we can migrate to a custom thing written in myrddin some day, but buildbot seems not totally horrible for some of what we need.

**Comment by oridb** [comment]
This is mostly working -- executing things over ssh is still needed, but the builder is running on https://eigenstate.org/contbuild/

If there are any other bits of code people think should be getting tested, let me know.

**Comment by kirbyfan64** [comment]
Uh, guys...I don't think this looks write on mobile:

![screenshot](https://s5.postimg.org/70r4g0ryf/Screenshot_20160910_095442.png)

**Comment by oridb** [comment]
Huh. That looks like a flexbox bug in your browser. Fu... n?

There's actually a Chromium bug report I put in for a similar issue: https://bugs.chromium.org/p/chromium/issues/detail?id=644621#c4

**Comment by oridb** [comment]
Ok, nope, I'm pretty sure I was just being stupid. It should be better now, I think.

**Comment by oridb** [comment]
So, it's now running builds on FreeBSD and OpenBSD, and it should be pretty easy to add any other platform that can be SSH'ed into. I'm going to call this done.
