### ISSUE TITLE
Union with func pointer incorrectly matched

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#65]
```
use std

type u = union
	`A
	`B ( -> void)
;;

const test = {o
	match o
	| (`A ):
		std.put("fail\n")
	| (`B _):
		std.put("pass\n")
	;;
}

const f = {
	-> void
}

const main = {
	test(`B f)
}
```

**Comment by oridb** [comment]
Yep, definitely a code gen issue. I'm a bit surprised, since the branch that we pick should only depend on the union tag in this case.

**Comment by andrewchambers** [comment]
my hunch was the function object had size or alignment wrong so it overwrites the tag somehow, interestingly this issue can't be worked around by wrapping the function in a single tuple (do you optimize this away?) or double tuple (crashes the compiler).

**Comment by oridb** [comment]
Dumping the decision tree shows that there was no accept for tag 1 (B). This seems to be because we didn't consider functions to be basic types in the match generation.
