### ISSUE TITLE
zero sized structs as parameter crash compiler

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#8]
```
use std

type s = struct
;;

const bar = {x
	-> 3
}

const main = {
	var x : s
	std.put("{}\n", bar(x))
}
```
6m: isel.c:410: blit: Assertion `szmodes[align] != ModeNone' failed.

**Comment by oridb** [comment]
This should definitely work. It should also theoretically be possible to pass 'void' as a value in these cases (for the sake of uniformity and generics).

There may be edge cases for slices and arrays with zero sized elements, so I expect there are going to be lots of bugs as I work through fixing this. At least those bugs are going to be isolated to zero sized types.

**Comment by andrewchambers** [comment]
No problem, I would like to even help fix some of these. For now I am not familiar enough with the implementation, so just created these issues as a reminder.

**Comment by oridb** [comment]
Fixed.
