### ISSUE TITLE
cannot unify empty struct with []

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#84]
```
use std

type u = union
	`T s
;;

type s = struct
;;

const main = {
	var s = `T []
}
```
```
ac@black:~/Desktop/bug$ mbld -b bug bug.myr  && ./bug
bug...
	6m	bug.myr 
bug.myr:12: type "s" incompatible with "$1187[0]" near Oucon:unknown
FAIL: "6m bug.myr"
```

**Comment by oridb** [comment]
Yes. [] is the empty array. There's no good way to solve the ambiguity between structs and arrays without at least one initializer, so I made [] into the empty array. The alternative is figuring out some way to resolve the issue after the fact, but this is hard.

Unless you come up with some good type rules for it, WONTFIX.

**Comment by kirbyfan64** [comment]
Would it be possible to at least improve the error message? It's not clear what `$1187[0]` and `Oucon:unknown` are...

**Comment by oridb** [comment]
Yes. That would be easy to do.
On Feb 13, 2016 12:51, Ryan Gonzalez <notifications@github.com> wrote:Would it be possible to at least improve the error message? It's not clear what $1187[0] and Oucon:unknown are...

**Comment by kirbyfan64** [comment]
Also...

Once I had a case like this in a toy compiler. What I ended up doing was modifying the function that determines if types are compatible to take a "context" node, which in this case would be the empty array node (`[]`). If the context was given and is an array literal, it can be casted to any struct.

Not sure how that would work with type inference, though...

**Comment by andrewchambers** [comment]
I see, I guess we need literal type hints before you can construct an empty struct.

**Comment by oridb** [comment]
The way this could potentially work for inference is that the type of a struct/array literal remains entirely unconstrained, and a delayed unification can take place at the end of type inference. But that's ugly, and would take thought to figure out if there are any knock on effects. At minimum, it would mean that you wouldn't be able to do

    x = []
    x.foo
