### ISSUE TITLE
unreachable code marked reachable causing compile failure

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#96]
```
use std

type u = union
	`A
	`B
	`C
	`D
;;

const foo = {
	while true
		match ("foo", `A)
		| (s, `A):
			-> true
		| (s, `B):
			-> false
		| (s, _):
			std.fatal("")
		;;
	;;
}

const main = {
	foo()
}
```
```
ac@black:~/src/qc$ mbld -R ~/Desktop/bug/bug.myr 
/tmp/runmyr4256087999...
	6m	/home/ac/Desktop/bug/bug.myr 
/home/ac/Desktop/bug/bug.myr:10: Reaches end of function without return
```

Don't know if this is an expected limitation or a bug.

**Comment by oridb** [comment]
A bit of both. We don't evaluate branches with constant conditions when doing data flow analysis. We probably should, at least for literals.

**Comment by oridb** [comment]
Going to close this for now -- I don't think I'm going to support this at the moment. Maybe later, I'll add a case for branches with a constant true/false condition.
