### ISSUE TITLE
types not correctly inferred using byenum 

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#97]
```
use std

const main = {
    var sl = [("foo", "bar")][:]
    for (i, (a, b)) in std.byenum(sl)
        std.put("{} {} {}\n", i, a, b)
    ;;
}
```

```
/tmp/runmyr4294926212...
    6m  /home/ac/Desktop/bug/bug.myr 
/home/ac/Desktop/bug/bug.myr:5: underconstrained type $1243 near Otup:(std.size,($1243,$1244))
FAIL: "6m /home/ac/Desktop/bug/bug.myr"
```

**Comment by oridb** [comment]
Probably an issue in delayed unification. I may have to make delayed unification loop until it converges :(

**Comment by andrewchambers** [comment]
well, if it needs to loop until steady state, at least it doesn't seem to happen much in practice.

**Comment by oridb** [comment]
Yeah, I'm careful about getting the order of unification right in the post check pass. I expect that in the worst case, it would take 2 or 3 loops, and eliminate most of them in each pass.

**Comment by oridb** [comment]
Also fixed.
