### ISSUE TITLE
Miscompilation

### ISSUE THREAD

**Issue by andrewchambers** [oridb/mc#99]
```
use std

const parsehash = {s -> std.option(byte[32])
	var hash
	var v1, v2
	
	if s.len != 64
		-> `std.None
	;;
	for var i = 0; i < 64; i += 2
		v1 = std.charval(s[i] castto(char), 16)
		v2 = std.charval(s[i+1] castto(char), 16)
		if v1 == -1 || v2 == -1
			-> `std.None
		;;
		hash[i/2] = (v1 << 4 | v2)
	;;
	-> `std.Some hash
}
const main = {
	std.put("{}\n", parsehash("096b35463d98282d8c6129150e5df4aec5690075e3dd941acc1eb5c559624834"))
}
```
fails when v1 and v2 are bytes, but succeeds when they are ints. The cause of the error seems to be a compiler bug when compiling std.charval with a byte sized return type.

The reproduction is not totally trivial as directly executing ``` std.charval('0', 16) ``` runs properly, needs further investigation.

**Comment by oridb** [comment]
Fixed.
